# Generated by Django 4.0.3 on 2022-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_followings_accept_date_followings_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followings',
            name='accept_date',
            field=models.DateTimeField(null=True),
        ),
    ]
